resources:
- name: project-release
  type: github-release
  source:
    owner: ((github-username))
    repository: ((github-repo))
    access_token: ((github-access-token))
    release: true
    pre_release: true
    
- name: ecr-docker-reg
  type: docker-image
  source:
    aws_access_key_id: ((aws-token))
    aws_secret_access_key: ((aws-secret))
    repository: ((aws-repo))
    
- name: git-repo
  type: git
  source:
    uri: ((github-repo-uri))
    branch: main
    username: ((github-username))
    password: ((github-access-token))

jobs:
- name: release-and-deploy
  plan:
  - get: project-release
    trigger: true
  - get: git-repo  
  - put: ecr-docker-reg
    params:
      build: ./git-repo
      tag_file: ./project-release/tag