resources:
- name: resource-repo
  type: git
  icon: github
  source:
    uri: https://github.com/ONS-Innovation/keh-github-scraper-batch.git
    branch: concourse

- name: scraper-image
  type: registry-image
  icon: docker
  source:
    repository: ((image-repo-name))
    username: ((registry-username))
    password: ((registry-password))
    tag: test

jobs:
- name:  build-and-push
  public: true
  plan:
  - get: resource-repo
    trigger: true
  - task: build-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: resource-repo
      outputs:
      - name: image
      params:
        CONTEXT: resource-repo
      run: # binary used to build the image
        path: build
  - put: scraper-image
    params:
      image: image/image.tar
