resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: latest


resources:
- name: resource-repo
  type: git
  icon: github
  source:
    uri: https://github.com/ONS-Innovation/keh-github-scraper-batch.git
    branch: concourse

- name: scraper-image
  type: registry-image
  icon: docker
  source:
    repository: ((image-repo-name))
    username: ((registry-username))
    password: ((registry-password))
    tag: ((container_ver))

- name: batch-repo
  type: git
  icon: github
  source:
    uri: https://github.com/ONS-Innovation/keh-scheduled-batch-tf-module
    branch: main
    username: ((github_access_token))
    password: x-oauth-basic

jobs:
- name:  build-and-push
  public: true
  plan:
  - get: resource-repo
    trigger: true
  - get: batch-repo
    trigger: false
  - task: build-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: resource-repo
      - name: batch-repo
      outputs:
      - name: image
      params:
        CONTEXT: resource-repo
      run: # binary used to build the image
        path: build
  - put: scraper-image
    params:
      image: image/image.tar
  - task: terraform
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      inputs:
      - name: resource-repo
      run:
        path: sh
        args:
        - -cx
        - |
          uname -m
          cd resource-repo/terraform/batch
          export AWS_ACCESS_KEY_ID=((aws_access_key_id))
          export AWS_SECRET_ACCESS_KEY=((aws_secret_access_key))
          export TF_VAR_github_token=((github_access_token))
          
          apt-add-repository https://cli.github.com/packages
          apt update
          apt install gh
          apt install git -y
          gh auth login --with-token ((github_access_token))

          apt install wget -y
          apt install unzip -y


          wget https://releases.hashicorp.com/terraform/1.11.4/terraform_1.11.4_linux_amd64.zip
          unzip terraform_1.11.4_linux_amd64.zip
          mv terraform /usr/local/bin/

          terraform init -backend-config=env/dev/backend-dev.tfbackend -reconfigure
          terraform apply \
           -var "aws_region=((aws_region))" \
           -var "aws_account_id=((aws_account_id))" \
           -var "aws_access_key_id=((aws_access_key_id))" \
           -var "aws_secret_access_key=((aws_secret_access_key))" \
           -var "domain=((domain))" \
           -var "container_ver=((container_ver))" \
           -var "source_bucket=((source_bucket))" \
           -var "github_org=((github_org))" \
           -auto-approve
          

