resources:
- name: resource-repo
  type: git
  icon: github
  source:
    uri: https://github.com/ONS-Innovation/keh-github-scraper-batch.git
    branch: concourse

- name: scraper-image
  type: registry-image
  icon: docker
  source:
    repository: ((image-repo-name))
    username: ((registry-username))
    password: ((registry-password))
    tag: latest

jobs:
- name:  build-and-push
  public: true
  plan:
  - get: resource-repo
    trigger: true
  - task: build-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: resource-repo
      outputs:
      - name: image
      params:
        CONTEXT: resource-repo
      run: # binary used to build the image
        path: build
  - put: scraper-image
    params:
      image: image/image.tar
  - task: terraform
    privileged: true
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: hashicorp/terraform}
      inputs:
      - name: resource-repo
      run:
        path: sh
        args:
        - -cx
        - |
          cd resource-repo/terraform/batch
          terraform init -backend-config=env/dev/backend-dev.tfbackend -reconfigure
          terraform apply \
           -var "aws_region=((aws_region))" \
           -var "aws_account_id=((aws_account_id))" \
           -var "aws_access_key_id=((aws_access_key_id))" \
           -var "aws_secret_access_key=((aws_secret_access_key))" \
           -var "aws_bucket_name=((aws_bucket_name))" \
           -var "domain=((domain))" \
           -var "container_ver=((container_ver))" \
           -var "source_bucket=((source_bucket))" \
            -var "github_org=((github_org))" \
           -auto-approve
          

